version: '3.4'
services:
  discoteque.api:
    image: discoteque:latest
    build:
      context: .
      dockerfile: Discoteque.API/Dockerfile
    ports:
      - "5044:5044"
      # - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__DefaultConnection=discotequePG=discoteque;Port=5432;Database=discoteque;Username=discotequeUsr;Password=localDk
    # depends_on:
    #   - db
    # networks:
    #   - app_network
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: discotequeUsr
      POSTGRES_PASSWORD: localDk
      POSTGRES_DB: discoteque
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - app_network
