FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 5044

ENV ASPNETCORE_URLS=http://+:5044

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Discoteque.sln", "."]
COPY ["Discoteque.API/Discoteque.API.csproj", "Discoteque.API/"]
COPY ["Discoteque.Business/Discoteque.Business.csproj", "Discoteque.Business/"]
COPY ["Discoteque.Data/Discoteque.Data.csproj", "Discoteque.Data/"]
COPY ["Discoteque.Tests/Discoteque.Tests.csproj", "Discoteque.Tests/"]
RUN dotnet restore
COPY . .
WORKDIR "/src/Discoteque.API"
RUN dotnet build "Discoteque.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Discoteque.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Discoteque.API.dll"]